const api =[

    {
        id:"f1",
        brand:"Bewakoof",
        title:"Bewakoof Official DC Merchandise Men's Printed Regular Fit Full Sleeve Round Neck Cotton T-Shirt",
        disc:"Fitted at Chest and Straight on Waist Down Bewakoof Official DC Merchandise Men's Printed Regular Fit Full Sleeve Round Neck Cotton T-Shirt",
        mrp:350,
        rmrp:1299,
        offer:73,
        img:"images/t-shirt_1.jpg",
    },
    {
      
        id:"f2",
        brand:"The Indian Garage Co",
        title:"The Indian Garage Co Men's Slim Fit Shirt",
        disc:"Customers like the quality, fit, and sizing of the shirt. They mention it has good feeting or fabrics. However, some customers have reported that the color is not as expected and it leaches color just once put in water.",
        mrp:448,
        rmrp:2099,
        offer:70,
        img:"images/t-shirt_2.jpg",
    },
    {
        id:"f3",
        brand:"The Souled Store Plaid",
        title:"The Souled Store Plaid: Brown Mustard and Black Men and Boys Relaxed fit Striped Full Sleeve Cotton Multicolored Men Relaxed Shirts Shirt For Men Casual Half Sleeves Regular Fit Printed Stylish Latest",
        disc:"Homegrown Indian Brand - One-stop-shop for Official Merch of all your favorite superheroes, films, TV shows and cartoons",
        mrp:1499,
        rmrp:1099,
        offer:25,
        img:"images/t-shirt_3.jpg",
    },
    {
        id:"f4",
        brand:"Puma",
        title:"Puma Men's Regular Fit T-Shirt",
        disc:"Designed for comfortable wear for sports and street-style, PUMA apparels are always fun to wear. Upgrade in style with wide range of apparels form the world’s leading and much-loved sports brand, PUMA.",
        mrp:499,
        rmrp:1299,
        offer:59,
        img:"images/t-shirt_4.jpg",
    },{
        id:"f5",
        brand:"lymio",
        title:"Lymio Men T-Shirt || T-Shirt for Men || Plain T Shirt || T-Shirt (Polo-18-21)",
        disc:"Men T Shirt || T-Shirt For Men || Plain T Shirt || T-Shirt",
        mrp:349,
        rmrp:1099,
        offer:89,
        img:"images/t-shirt_5.jpg",
    },
    {
        id:"f6",
        brand:"DEELMO",
        title:"DEELMO Men's Cotton Blend Mandarin Collar Self One Design Full Sleeve Casual Short Kurta",
        disc:"Breathable and Comfortable Cotton Blend: Enjoy the softness and breathability of our premium cotton blend fabric.",
        mrp:494,
        rmrp:2199,
        offer:78,
        img:"images/t-shirt_6jpg.jpg",
    },
    {
        id:"f7",
        brand:"NIMAVAT FABS",
        title:"NIMAVAT FABS Men's Printed Cotton Relaxed Fit Long Sleeve Mandarian Collared Casual Lightweight Comfortable Short Kurta (T_E_220624)",
        disc:"This Kurta made of qulity material.Classy & Charming Look Upgrade your fashion quotient with these shirts for men as they give you a new look and appeal.",
        mrp:499,
        rmrp:2099,
        offer:83,
        img:"images/t-shirt_7.jpg",
    },
  
    // pants
    {
        id:"f8",
        brand:"The Souled Store",
        title:"The Souled Store Men TSS Originals: Navy Printed Joggers",
        disc:"",
        mrp:999,
        rmrp:1999,
        offer:50,
        img:"images/pant_1.jpg",
    },
  
    {
        id:"f9",
        brand:"Lymio",
        title:"Lymio Men Cargo || Men Cargo Pants || Men Cargo Pants Cotton || Cargos for Men (Cargo-09-12)",
        disc:"Men Cargo || Men Cargo Pants || Men Cargo Pants Cotton || Cargos for Men Cargos for Men (Cargo-09-12",
        mrp:549,
        rmrp:4999,
        offer:89,
        img:"images/pant_2.jpg",
    },
    {
        id:"f10",
        brand:"Lymio  ",
        title:"Lymio Men Cargo || Men Cargo Pants || Men Cargo Pants Cotton || Cargos for Men (Cargo-01-04)",
        disc:"Breathable and Comfortable Cotton Blend: Enjoy the softness and breathability of our premium cotton blend fabric.",
        mrp:499,
        rmrp:4099,
        img:"images/pant_3.jpg",
        offer:50,
    },
    {
        id:"f11",
        brand:"PETER ENGLAND",
        title:"PETER ENGLAND JEANS Men Pants",
        disc:"Breathable and Comfortable Cotton Blend: Enjoy the softness and breathability of our premium cotton blend fabric.",
        mrp:769,
        rmrp:1699,
        offer:55,
        img:"images/p.jpg",
    },
    {
        id:"f12",
        brand:"BLACK FLU",
        title:"BLACK FLU Men Tapered Fit Mid-Rise Jeans Plus Size Men's Regular Fit Jeans Set-1",
        disc:"Men's jeans are a staple in casual and everyday fashion. They typically feature a sturdy denim fabric and come in various styles, fits, and washes to suit different preferences and occasions. Here's a general Men's jeans are commonly made from denim",
        mrp:1299,
        rmrp:1999,
        offer:35,
        img:"images/pant_4.jpg",
    },
            // women
            {
                id:"w1",
                brand :"Leriya fashion",
                title:"Leriya Fashion Women Dress | One Piece Dress for Women | Dresses for Women | Trendi Dress for Women | Dress",
                disc:"Soft rayon blend: this one-piece dress for women is made of a soft rayon blend material, featuring with floral printed beach dress for women.Style & length: this birthday dress for women western has midi length",
                mrp:379,
                rmrp:1099,
                offer:87,
                img:"female/fe1.jpg",
            },
        
            {
                id:"w2",
                brand:"Leriya Fashion",
                title:"Leriya Fashion Oversized Shirt for Women | Shirt for Women Stylish Western | Women Long Shirt",
                disc:"Versatile Style: Leriya Fashion women oversized printed shirt is used for Western Wear, birthday party wear, Office wear, casual wear, Beach Wear, Summer Wear, Hangouts, Picnic, Vacation Wear",
                mrp:339,
                rmrp:1099,
                offer:83,
                img:"female/fe2.jpg",
            },
        
            {
                id:"w3",
                brand:"ANNI DESIGNER",
                title:" ANNI DESIGNER Women's Cotton Blend Straight Printed Kurta with Pant & Dupatta",
                disc:"Kurta Set Fabric: Cotton Blend || Kurta Set Color :- Navy Blue Style: Straight || Length: Calf Length || Sleeves: 3/4 Sleeves || Size Chart- Kurta-S-36 in, M-38 in , L-40 in , XL-42 in , XXL-44 in,Pant :- S-28 in, M-30 ",
                mrp:579,
                rmrp:2599,
                offer:70,
                img:"female/fe3.jpg",
            },
            {
                id:"w4",
                brand:"KOTTY",
                title:"KOTTY Women's Single Breasted Relaxed Fit Shawl Collar 3/4 Sleeve Blazer",
                disc:"Fabric: Crafted from luxurious viscose Rayon for comfort and style.Fit: Designed with a flattering relaxed fit for versatile styling options.Wash Care: Easily maintainable with machine wash convenience.",
                mrp:299,
                rmrp:85,
                offer:1999,
                img:"female/fe4.jpg",
            },{
                id:"w5",
                brand:"MAX",   
                title:"Max Women Knee Length Dress",
                disc:"Women Floral Printed Midi Dress Women Floral Printed Midi Dress Color: Pink Pattern: Printed",
                mrp:799,
                rmrp:999,
                offer:20,
                img:"female/fe5.jpg ",
            },{
                id:"w6",
                brand:"The Souled Store",
                title:"The Souled Store Official Harry Potter: Magical Women and Girls Long Sleeves Collared Neck Button Front Brown All Over Printed Cotton Blend Boyfriend Shirts",
                disc:"HOMEGROWN INDIAN BRAND : One-stop-shop for Official Merch of All Your Favorite Superheroes, Films, TV Shows and Cartoons",
                mrp:1499,
                rmrp:1999,
                offer:25,
                img:"female/fe6.jpg",
            },{
                id:"w7",
                brand:"KOTTY",
                title:"KOTTY Women High Rise Relaxed Fit Cotton Lycra Blend Ankle Length Jeans",
                disc:"Fabric: Constructed with a durable cotton lycra blend, offering a perfect balance of comfort and flexibility for your active lifestyle.",
                mrp:442,
                rmrp:9,
                offer:78,
                img:"female/fe7.jpg",
            },{
                id:"w8",
                brand:"ADBUCKS",
                title:"ADBUCKS Womens Slim Fit Denim Lycra Stretchable Capri Mid Rise with Elasticated Waistband (Plus Size Also Available)",
                disc:"Silky Soft Denim Lycra Stretchable Capri with Elasticated Waistband. Plus Size option also available, click on the drop-down size list above. Size options include 28, 30, 32, 34, 36, 38, 40.",
                mrp:699,
                rmrp:1499,
                offer:53,
                img:"female/fe8.jpg",
            },{
                id:"w9",
                brand:"GoSriKi",
                title:"GoSriKi Women's Cotton Blend Embroidered Straight Kurta with Pant & Dupatta",
                disc:"Kurta Set Fabric: Cotton Blend || Kurta Set Color :- Blue Style: Straight || Length: Calf Length || Sleeves: 3/4 Sleeves ",
                mrp:579,
                rmrp:76,
                offer:2599,
                img:"female/fe9.jpg",
            },
    // mobile
    {
        id:"m1",
        name:"Redmi 13",
        disc:"Redmi 13 5G, Orchid Pink, 6GB+128GB | India Debut SD 4 Gen 2 AE | 108MP Pro Grade Camera | 6.79in Largest Display in Segment",
        img:"mo1.jpg",
        mrp:13999,
        rmrp:17000,
        offer:25,   
       },
       
       {
           id:"m2",
           name:"Redmi Note 13 Pro",
           disc:"Redmi Note 13 Pro (Coral Purple, 8GB RAM, 128GB Storage) | 1.5K AMOLED | 200MP Hi-Res Camera | Flagship 4nm SD 7s Gen 2 | 67W TurboCharge",
           img:"mobiles/mo4.jpg",
           mrp:22999,
           rmrp:28999,
           offer:25,   
          },
      
          {
           id:"m3",
           name:"OnePlus Nord CE4 Lite",
           disc:"OnePlus Nord CE4 Lite 5G (Super Silver, 8GB RAM, 128GB Storage)",
           mrp:13008,
           img:"mobiles/mo7.jpg",
           rmrp:20999, 
           offer:5,   
          },
          
       {
           id:"m4",
           name:"Motorola Edge 50 Pro",
           disc:"Motorola Edge 50 Pro 5G with 125W Charger (Luxe Lavender, 256 GB) (12 GB RAM)",
           mrp:32498,
           img:"https://m.media-amazon.com/images/I/715aoVxQNTL._SX679_.jpg",
           rmrp:41999,
           offer:23,   
          },
          {
           id:"m5",
           name:"Samsung Galaxy S24 Ultra",
           disc:"Samsung Galaxy S24 Ultra 5G AI Smartphone (Titanium Gray, 12GB, 512GB Storage)",
           mrp:131999,
           img:"mobiles/mo6.jpg",
           rmrp:41999,
           offer:23,   
          },
          {
           id:"m6",
           name:"Samsung Galaxy S22 ",
           disc:"Samsung Galaxy S22 5G (Phantom Black, 8GB, 128GB Storage) with No Cost EMI/Additional Exchange Offers",
           mrp:36170,
           img:"mobiles/mo8.jpg",
           rmrp:85999,
           offer:58,   
          },
          {
           id:"m7",
           name:"Lava Agni 2 ",
           disc:"Lava Agni 2 5G (Glass Viridian, 8GB RAM, 256GB Storage) | India's First Dimensity 7050 Processor | 120 Hz Curved Amoled Display | 13 5G Bands | Superfast 66W Charging | Clean Android",
           mrp:16999,
           img:"mobiles/mo9.jpg",
           rmrp:35999,
           offer:35,   
          },
        //   laptop

            {
        id:"l1",
        title:"Acer ALG 12th Gen Intel Core i5 Gaming Laptop (16GB RAM/512GB SSD/4GB RTX 2050 Graphics/60Hz/Win11Home/Wifi 6) AL15G-52, 39.62cm (15.6 inch) FHD Display, Premium Metal Body, Steel Gray, 1.99KG",
        disc:"Powerful Productivity: 12th Generation Intel Core i5-12450H Dual Core processor delivers unmatched speed and intelligence, enabling impressive creating, productivity, and gaming experiences. With Turbo Boost Technology, get up to 4.4GHz for your high-demand applications. Connectivity Technology: Wi-Fi, Bluetooth, HDMI",
        img:"laptop/lap1.jpg",
        mrp:50999,
        rmrp:89990,
        offer:43,   
       },

       {
        id:"l2",
        title:"Acer Nitro V Gaming Laptop 13th Gen Intel Core i5-13420H with RTX 4050 Graphics 6GB VRAM, 144Hz Display (16GB DDR5/512GB SSD/Windows 11 Home/Wi-Fi 6),15.6(39.6cms) FHD ANV15-51",
       disc:"Processor: Intel Core i5-13420H processor - 8 cores, max turbo up to 4.60 Ghz | RAM : 16 GB of DDR5 system memory, upgradable to 32 GB (Memory Frequency: Up to 5200 MT/s) Display : 15.6 display with IPS (In-Plane Switching) technology, ",
       img:"laptop/lap2.jpg",
       mrp:74990,
       rmrp:103999,
       offer:28,   
      },

{
    id:"l3",
    title:"ASUS TUF F17 Gaming Laptop, Intel Core i5-11400H 11th Gen, 17.3-inch (43.94 cm) 144Hz, (8GB RAM/512GB SSD/4GB NVIDIA GeForce RTX 2050/Windows 11/ RGB Backlit KB/Black/2.30 kg), FX706HF-HX018W",
   disc:"Processor: Intel Core i5-11400H Processor 2.7 GHz (12M Cache, up to 4.5 GHz, 6 Cores) improving multitasking performance & Designed to handle high loadsStorage: 512GB PCIe 3.0 NVMe M.2 SSD with additional 1x M.2 Slot for SSD Storage expansion | Memory: 16GB SO-DIMM DDR4 3200MHz Support Up to 32GB 2x SO-DIMM slots",
   img:"laptop/lap3.jpg",
   mrp:48990,
   rmrp:75990,
   offer:36,   
  },
  {
    id:"l4",
   disc:" HP Victus Gaming Laptop,Windows 11 Home,AMD Ryzen 5 5600H,4Gb RTX 3050 Gpu,15.6-Inch (39.6 Cm),Fhd,IPS,144Hz,16Gb Ddr4,512Gb Ssd,Backlit Kb,B&O,9Ms Response Time,Dual Speakers (Blue,2.37 Kg),Fb0106Ax",
   title:"HP Victus Gaming Laptop,Windows 11 Home,AMD Ryzen 5 5600H,4Gb RTX 3050 Gpu,15.6-Inch (39.6 Cm),Fhd,IPS,144Hz,16Gb Ddr4,512Gb Ssd,Backlit Kb,B&O,9Ms Response Time,Dual Speakers (Blue,2.37 Kg),Fb0106Ax",
   img:"laptop/fe4.jpg",
   mrp:57990,
   rmrp:84689,
   offer:32,   
  },{
    id:"l5",
   disc:"Processor : AMD Ryzen 9 8945H Processor 4GHz (24MB Cache, up to 5.2 GHz, 8 cores, 16 Threads) AMD Ryzen AI up to 39 TOPsDisplay :15.6-inch, FHD (1920 x 1080) 16:9, 144hz, 250 nits Brightness, Keyboard : Backlit Chiclet Keyboard 1-Zone RGB",
   title:"ASUS TUF Gaming A15, 15.6 FHD 144Hz 250nits, AMD Ryzen 9 8945H Processor, Gaming Laptop (32GB RAM/1TB SSD NVIDIA GeForce RTX 4060/Windows 11/Office Home/Mecha Gray/2.2 Kg), FA507UV-LP137WS",
   img:"laptop/lap5.jpg",
   mrp:141400,
   rmrp:189000,
   offer:25,   
  }
  ,{
    id:"l6",
   disc:"Processor: AMD Ryzen 7 7840HS (up to 5.1 GHz max boost clock, 16 MB L3 cache, 8 cores, 16 threads)| Memory: 32 GB DDR5-5600 MHz RAM | Storage: 1TB PCIe Gen4 NVMe TLC M.2 SSD Display : 16.1 (40.9cm)diagonal, FHD (1920 x 1080), 165 Hz, 7 ms response time, IPS, micro-edge, anti-glare, Low Blue Light, 300 nits, 100% sRGB",
   title:"HP OMEN Gaming Laptop, AMD Ryzen™ 7 7840HS,16.1inch(40.9cm),FHD,Anti-Glare,32GB RAM DDR5,1TB SSD,8GB RTX 4060 GPU,Windows 11,MSO21,Shadow Black,2.37kg,16-xd0017AX",
   img:"laptop/lap6.jpg",                                                           
   mrp:125990,
   rmrp:184269,
   offer:14,   
  }
  ,{
    id:"l7",
   disc:"Features- Powerful performance with the latest in CPU(13G HX-series)/GPU (RTX 40-series) technology: Uncompromised gaming experience with a larger screen, full-sized CherryMX keyboard",
   img:"laptop/jap7.jpg",
   title:" Dell Alienware m18 R1 Gaming Laptop,Intel Core i9- 13900HX/32GB/1TB SSD/NVIDIA RTX 4080 12GB GDDR6/18.0 (45.72cm) QHD 165Hz/Win 11+MSO'21/15 Month McAfee/Backlit KB per-Key AlienFX/Dark Metallic Moon",
   mrp:343019,
   rmrp:469654,
   offer:27,   
  },{
    id:"l8",
   disc:"AI Enabled Processor: Intel Evo Core Ultra 9 185H | 16C (6P + 8E + 2LPE) / 22T, Max Turbo up to 5.1Ghz | 16 Cores | 22 Threads | Cache: 24MBMemory and Storage: 32GB RAM LPDDR5x-7467 | 1 TB SSD (Expandable upto 2TB) || Graphics: Integrated Intel Arc Graphics",
   img:"laptop/lap8.webp",
   title:"Lenovo IdeaPad Pro 5 Intel Evo Core Ultra 9 185H Built-in AI 14 (35.56cm) 2.8K-OLED 400Nits 120Hz Laptop (32GB/1TB SSD/Win11/MSO 21/FHD+IR Camera/1Yr ADP Free/3 Mon Game Pass/Grey/1.4Kg), 83D2001GIN",
   mrp:107990,
   rmrp:146090,
   offer:27,   
   },
        ]
        export default api